'use strict';

const CARDFACES = [
  'clubs-02',
  'clubs-03',
  'clubs-04',
  'clubs-05',
  'clubs-06',
  'clubs-07',
  'clubs-08',
  'clubs-09',
  'clubs-10',
  'clubs-jack',
  'clubs-queen',
  'clubs-king',
  'clubs-ace',

  'diamonds-02',
  'diamonds-03',
  'diamonds-04',
  'diamonds-05',
  'diamonds-06',
  'diamonds-07',
  'diamonds-08',
  'diamonds-09',
  'diamonds-10',
  'diamonds-jack',
  'diamonds-queen',
  'diamonds-king',
  'diamonds-ace',

  'hearts-02',
  'hearts-03',
  'hearts-04',
  'hearts-05',
  'hearts-06',
  'hearts-07',
  'hearts-08',
  'hearts-09',
  'hearts-10',
  'hearts-jack',
  'hearts-queen',
  'hearts-king',
  'hearts-ace',

  'spades-02',
  'spades-03',
  'spades-04',
  'spades-05',
  'spades-06',
  'spades-07',
  'spades-08',
  'spades-09',
  'spades-10',
  'spades-jack',
  'spades-queen',
  'spades-king',
  'spades-ace',

  'joker-black',
  'joker-red'
];

export {CARDFACES};
